version: "3.7"
services:
  api:
    container_name: api_dev
    build: ./api/
    ports:
      - "4001:3000"
    networks:
      - dev_net
    depends_on:
      - postgres
    environment:
      - DB_TYPE=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=dev
      - HASH_SALT=10
    volumes:
      - ./:/usr/src/app
    command: yarn start:dev
  postgres:
    container_name: postgres_dev
    image: postgres
    ports:
      - "4002:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
    networks:
      - dev_net
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: dev
  web:
    container_name: web_dev
    build: 
      context: ./web/
      args:
        - BASE_API_URL=http://localhost:4001
    ports:
      - "4000:80"

networks:
  dev_net:
volumes:
  postgres_data_dev: