version: "3.7"
services:
  api:
    container_name: api
    build: ./api/
    ports:
      - "3080:3080"
    networks:
      - webnet
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: dev
  web:
    container_name: web
    build: ./web/
    ports:
      - "3333:80"

networks:
  webnet:
volumes:
  postgres_data: